"""phase 3b bid optimization tables

Revision ID: 1ecb571dd710
Revises: b2f1a7c9d3e4
Create Date: 2026-07-26 01:40:46.045413
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "1ecb571dd710"
down_revision: str | None = "b2f1a7c9d3e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bid_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_code", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "file_type",
            postgresql.ENUM("XLSX", "CSV", "TSV", name="file_type", create_type=False),
            nullable=False,
        ),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("route_count", sa.Integer(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bid_files")),
    )
    op.create_index(op.f("ix_bid_files_checksum"), "bid_files", ["checksum"], unique=True)
    op.create_index(
        op.f("ix_bid_files_provider_code"), "bid_files", ["provider_code"], unique=False
    )
    op.create_table(
        "bid_file_routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bid_file_id", sa.Integer(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("provider_code", sa.String(length=128), nullable=False),
        sa.Column("origin", sa.String(length=64), nullable=False),
        sa.Column("destination", sa.String(length=64), nullable=False),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.Column(
            "current_override_cpc",
            sa.Numeric(precision=14, scale=4, asdecimal=False),
            nullable=True,
        ),
        sa.Column("origin_is_iata", sa.Boolean(), nullable=False),
        sa.Column("destination_is_iata", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bid_file_id"],
            ["bid_files.id"],
            name=op.f("fk_bid_file_routes_bid_file_id_bid_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bid_file_routes")),
        sa.UniqueConstraint("bid_file_id", "origin", "destination", name="uq_bid_route_segment"),
    )
    op.create_index(
        op.f("ix_bid_file_routes_bid_file_id"), "bid_file_routes", ["bid_file_id"], unique=False
    )
    op.create_table(
        "optimization_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bid_file_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", name="run_status"),
            nullable=False,
        ),
        sa.Column("ruleset_version", sa.String(length=64), nullable=False),
        sa.Column("total_routes", sa.Integer(), nullable=False),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("unmatched_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("recommendation_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(length=1024), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bid_file_id"],
            ["bid_files.id"],
            name=op.f("fk_optimization_runs_bid_file_id_bid_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optimization_runs")),
    )
    op.create_index(
        op.f("ix_optimization_runs_bid_file_id"), "optimization_runs", ["bid_file_id"], unique=False
    )
    op.create_index(
        op.f("ix_optimization_runs_status"), "optimization_runs", ["status"], unique=False
    )
    op.create_table(
        "bid_recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("optimization_run_id", sa.Integer(), nullable=False),
        sa.Column("bid_file_route_id", sa.Integer(), nullable=False),
        sa.Column("route_summary_id", sa.Integer(), nullable=True),
        sa.Column(
            "match_status",
            sa.Enum(
                "MATCHED",
                "UNMATCHED_NO_HISTORY",
                "UNMATCHED_NON_IATA",
                "SKIPPED_EXCLUDED",
                name="match_status",
            ),
            nullable=False,
        ),
        sa.Column("origin", sa.String(length=64), nullable=False),
        sa.Column("destination", sa.String(length=64), nullable=False),
        sa.Column("current_bid", sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=True),
        sa.Column(
            "recommended_bid", sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=True
        ),
        sa.Column("difference", sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=True),
        sa.Column("pct_change", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reason", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bid_file_route_id"],
            ["bid_file_routes.id"],
            name=op.f("fk_bid_recommendations_bid_file_route_id_bid_file_routes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["optimization_run_id"],
            ["optimization_runs.id"],
            name=op.f("fk_bid_recommendations_optimization_run_id_optimization_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["route_summary_id"],
            ["route_summaries.id"],
            name=op.f("fk_bid_recommendations_route_summary_id_route_summaries"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bid_recommendations")),
    )
    op.create_index(
        op.f("ix_bid_recommendations_match_status"),
        "bid_recommendations",
        ["match_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bid_recommendations_optimization_run_id"),
        "bid_recommendations",
        ["optimization_run_id"],
        unique=False,
    )
    op.create_table(
        "rule_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bid_recommendation_id", sa.Integer(), nullable=False),
        sa.Column("rule_key", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.String(length=32), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("signal", sa.Float(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["bid_recommendation_id"],
            ["bid_recommendations.id"],
            name=op.f("fk_rule_results_bid_recommendation_id_bid_recommendations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_results")),
    )
    op.create_index(
        op.f("ix_rule_results_bid_recommendation_id"),
        "rule_results",
        ["bid_recommendation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rule_results_bid_recommendation_id"), table_name="rule_results")
    op.drop_table("rule_results")
    op.drop_index(
        op.f("ix_bid_recommendations_optimization_run_id"), table_name="bid_recommendations"
    )
    op.drop_index(op.f("ix_bid_recommendations_match_status"), table_name="bid_recommendations")
    op.drop_table("bid_recommendations")
    op.drop_index(op.f("ix_optimization_runs_status"), table_name="optimization_runs")
    op.drop_index(op.f("ix_optimization_runs_bid_file_id"), table_name="optimization_runs")
    op.drop_table("optimization_runs")
    op.drop_index(op.f("ix_bid_file_routes_bid_file_id"), table_name="bid_file_routes")
    op.drop_table("bid_file_routes")
    op.drop_index(op.f("ix_bid_files_provider_code"), table_name="bid_files")
    op.drop_index(op.f("ix_bid_files_checksum"), table_name="bid_files")
    op.drop_table("bid_files")
    # ### end Alembic commands ###
