"""phase 2 ingestion tables

Revision ID: 59e19d3e8bf0
Revises:
Create Date: 2026-07-25 07:45:01.127489
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "59e19d3e8bf0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "route_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=3), nullable=False),
        sa.Column("destination", sa.String(length=3), nullable=False),
        sa.Column("device", sa.Enum("DESKTOP", "MOBILE", name="device_type"), nullable=False),
        sa.Column("total_reports", sa.Integer(), nullable=False),
        sa.Column("total_impressions", sa.BigInteger(), nullable=False),
        sa.Column("total_clicks", sa.BigInteger(), nullable=False),
        sa.Column("average_ctr", sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True),
        sa.Column("average_cpc", sa.Numeric(precision=16, scale=4, asdecimal=False), nullable=True),
        sa.Column(
            "average_position", sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True
        ),
        sa.Column(
            "total_spend", sa.Numeric(precision=16, scale=4, asdecimal=False), nullable=False
        ),
        sa.Column("total_bookings", sa.BigInteger(), nullable=False),
        sa.Column("last_report_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_summaries")),
        sa.UniqueConstraint("origin", "destination", "device", name="uq_route_summary_segment"),
    )
    op.create_table(
        "uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("file_type", sa.Enum("XLSX", "CSV", "TSV", name="file_type"), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "upload_status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="upload_status"),
            nullable=False,
        ),
        sa.Column("report_type", sa.String(length=32), nullable=True),
        sa.Column("imported_rows", sa.Integer(), nullable=False),
        sa.Column("skipped_rows", sa.Integer(), nullable=False),
        sa.Column("processing_ms", sa.Integer(), nullable=True),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.String(length=1024), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploads")),
    )
    op.create_index(op.f("ix_uploads_checksum"), "uploads", ["checksum"], unique=True)
    op.create_index(op.f("ix_uploads_upload_status"), "uploads", ["upload_status"], unique=False)
    op.create_table(
        "performance_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column(
            "report_type", sa.Enum("INLINE", "DYNAMIC_INLINE", name="report_type"), nullable=False
        ),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("origin", sa.String(length=3), nullable=False),
        sa.Column("destination", sa.String(length=3), nullable=False),
        sa.Column("device", sa.Enum("DESKTOP", "MOBILE", name="device_type"), nullable=False),
        sa.Column("impressions", sa.BigInteger(), nullable=False),
        sa.Column("clicks", sa.BigInteger(), nullable=False),
        sa.Column("ctr", sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True),
        sa.Column("avg_cpc", sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=True),
        sa.Column("spend", sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=False),
        sa.Column("bookings", sa.Integer(), nullable=False),
        sa.Column(
            "avg_position", sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("fk_performance_reports_upload_id_uploads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_performance_reports")),
    )
    op.create_index(
        op.f("ix_performance_reports_report_date"),
        "performance_reports",
        ["report_date"],
        unique=False,
    )
    op.create_index(
        "ix_performance_reports_route",
        "performance_reports",
        ["origin", "destination", "device"],
        unique=False,
    )
    op.create_index(
        op.f("ix_performance_reports_upload_id"), "performance_reports", ["upload_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_performance_reports_upload_id"), table_name="performance_reports")
    op.drop_index("ix_performance_reports_route", table_name="performance_reports")
    op.drop_index(op.f("ix_performance_reports_report_date"), table_name="performance_reports")
    op.drop_table("performance_reports")
    op.drop_index(op.f("ix_uploads_upload_status"), table_name="uploads")
    op.drop_index(op.f("ix_uploads_checksum"), table_name="uploads")
    op.drop_table("uploads")
    op.drop_table("route_summaries")
    # ### end Alembic commands ###
