"""phase 3c deterministic recommendation fields

Revision ID: 63fed26e1c8e
Revises: 1ecb571dd710
Create Date: 2026-07-26 03:17:58.723858
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "63fed26e1c8e"
down_revision: str | None = "1ecb571dd710"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # New enum types must be created before columns reference them (add_column
    # does not create them automatically).
    bind = op.get_bind()
    action_enum = postgresql.ENUM(
        "KEEP", "INCREASE", "MANUAL_REVIEW", "INSUFFICIENT_DATA", name="recommendation_action"
    )
    confidence_enum = postgresql.ENUM("HIGH", "MEDIUM", "LOW", name="confidence_level")
    action_enum.create(bind, checkfirst=True)
    confidence_enum.create(bind, checkfirst=True)

    op.add_column(
        "bid_recommendations",
        sa.Column(
            "device",
            postgresql.ENUM("ALL", "DESKTOP", "MOBILE", name="device_type", create_type=False),
            nullable=True,
        ),
    )
    op.add_column(
        "bid_recommendations",
        sa.Column(
            "action",
            postgresql.ENUM(
                "KEEP",
                "INCREASE",
                "MANUAL_REVIEW",
                "INSUFFICIENT_DATA",
                name="recommendation_action",
                create_type=False,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "bid_recommendations", sa.Column("rule_triggered", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "bid_recommendations",
        sa.Column(
            "confidence_level",
            postgresql.ENUM("HIGH", "MEDIUM", "LOW", name="confidence_level", create_type=False),
            nullable=True,
        ),
    )
    op.add_column("bid_recommendations", sa.Column("manual_review", sa.Boolean(), nullable=False))
    op.add_column(
        "bid_recommendations",
        sa.Column(
            "current_position", sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True
        ),
    )
    op.add_column(
        "bid_recommendations",
        sa.Column("ctr", sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True),
    )
    op.add_column("bid_recommendations", sa.Column("clicks", sa.BigInteger(), nullable=True))
    op.add_column("bid_recommendations", sa.Column("impressions", sa.BigInteger(), nullable=True))
    op.add_column(
        "bid_recommendations",
        sa.Column("spend", sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=True),
    )
    op.create_index(
        op.f("ix_bid_recommendations_action"), "bid_recommendations", ["action"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bid_recommendations_action"), table_name="bid_recommendations")
    op.drop_column("bid_recommendations", "spend")
    op.drop_column("bid_recommendations", "impressions")
    op.drop_column("bid_recommendations", "clicks")
    op.drop_column("bid_recommendations", "ctr")
    op.drop_column("bid_recommendations", "current_position")
    op.drop_column("bid_recommendations", "manual_review")
    op.drop_column("bid_recommendations", "confidence_level")
    op.drop_column("bid_recommendations", "rule_triggered")
    op.drop_column("bid_recommendations", "action")
    op.drop_column("bid_recommendations", "device")
    bind = op.get_bind()
    postgresql.ENUM(name="recommendation_action").drop(bind, checkfirst=True)
    postgresql.ENUM(name="confidence_level").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
